name: CMake Multi-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Set build directory
        id: vars
        run: echo "BUILD_DIR=${{ github.workspace }}/build" >> $GITHUB_ENV

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B "$BUILD_DIR" -S "$GITHUB_WORKSPACE" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }} -- -j$(nproc)
          else
            cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }} -- /m
          fi

      - name: Run tests
        working-directory: ${{ env.BUILD_DIR }}
        shell: bash
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
