name: CMake Multi-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.os }} | ${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.4'

      # Linux dependencies
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libopencv-dev libeigen3-dev libopenexr-dev

      # Windows dependencies
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install pkgconfiglite
          # Use vcpkg for consistency
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install opencv eigen3 openexr
          echo "CMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV

      # Configure
      - name: Configure with CMake
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }}
          else
            cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          fi

      # Build
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      # Install
      - name: Install
        run: cmake --install build --prefix instdir
